diff --git a/Makefile b/Makefile
index c9970e5..0669019 100755
--- a/Makefile
+++ b/Makefile
@@ -72,7 +72,7 @@ DEFAULT_IASL_VER := $(shell $(PARSE_PLATFORMS_TOOL) -c $(PLATFORMS_CONFIG) -p $(
 IASL_VER ?= $(if $(VER_GT_104),$(DEFAULT_IASL_VER),20200110)
 
 # efitools version
-EFITOOLS_VER := 1.8.1
+EFITOOLS_VER := 1.9.2
 
 # File path variables
 LINUXBOOT_FMT := $(if $(shell echo $(BUILD_LINUXBOOT) | grep -w 1),_linuxboot,)
@@ -210,7 +210,9 @@ _check_efitools:
 	$(eval EFITOOLS_REPO_URL := https://github.com/vathpela/efitools.git)
 	$(eval export PATH := $(EFI_TOOLS_DIR):$(PATH))
 
-	@if which $(CERT_TO_EFI_SIG_LIST) &>/dev/null && which $(SIGN_EFI_SIG_LIST) &>/dev/null && $(CERT_TO_EFI_SIG_LIST) --version 2>/dev/null | grep $(EFITOOLS_VER); then \
+	@if which $(CERT_TO_EFI_SIG_LIST) &>/dev/null && which $(SIGN_EFI_SIG_LIST) &>/dev/null && \
+		[ `$(CERT_TO_EFI_SIG_LIST) --version | cut -d' ' -f2 | tr -d .` -ge `echo $(EFITOOLS_VER) | tr -d .` ]; \
+	then \
 		echo "OK"; \
 	else \
 		echo -e "Not Found\nDownloading and building efitools..."; \
